# .github/workflows/pr-checks.yml
name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile project (dry run)
        run: ./gradlew assembleDebug --dry-run

      - name: Run Detekt (allow failures)
        if: success()
        run: ./gradlew detekt
        continue-on-error: true

      - name: Merge Detekt Reports
        if: always()
        run: |
          mkdir -p merged-report
          echo "# ðŸ” Detekt Report Summary" > merged-report/detekt.md
          echo "" >> merged-report/detekt.md
          
          for file in $(find . -path "*/build/reports/detekt/detekt.md"); do
            echo "## ðŸ“„ ${file}" >> merged-report/detekt.md
            cat "$file" >> merged-report/detekt.md
            echo -e "\n\n" >> merged-report/detekt.md
          done

      - name: Publish Detekt Report
        if: always()
        uses: IlyaSuponev/detekt-pr-reporter-action@v1.0.5
        with:
          report_path: merged-report/detekt.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Unit Tests
        if: success()
        run: ./gradlew test
