# .github/workflows/pr-checks.yml
name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Merge Detekt Reports
        run: |
          mkdir -p merged-report
          echo "# ðŸ” Detekt Report Summary" > merged-report/detekt.md
          echo "" >> merged-report/detekt.md
          
          for file in $(find . -path "*/build/reports/detekt/detekt.md"); do
            echo "## ðŸ“„ ${file}" >> merged-report/detekt.md
            cat "$file" >> merged-report/detekt.md
            echo -e "\n\n" >> merged-report/detekt.md
          done

      - name: Publish Detekt Report
        uses: IlyaSuponev/detekt-pr-reporter-action@v1.0.5
        with:
          report_path: merged-report/detekt.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build Debug APK
        run: ./gradlew assembleDebug